sudo: required

language: go

go:
  - 1.6
  - tip

services:
  - docker

install:
  - go get -u github.com/Masterminds/glide
  - docker-compose up -d

script: go test -tag=\!integration -v $(glide novendor)
