sudo: required

language: go

go:
  - 1.6
  - 1.7
  - tip

services:
  - docker

install:
  - go get -u github.com/Masterminds/glide
  - GOOS=linux GOGC=off go build -v

script: go test -v -race $(glide novendor)
