sudo: required

language: go

go:
  - 1.6
  - tip

services:
  - docker

install:
  - go get -u github.com/Masterminds/glide
  - GOOS=linux GOGC=off go build -v

script: go test -tags=\!integration -v $(glide novendor)
